[features]
seeds = false
skip-lint = false
[programs.localnet]
guess_number = "C6y8ezsrZwT3h4SEAsPHc6A1V2Gep5kv1WmEjDN7PGCW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hangyeonghyeon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
